"""empty message

Revision ID: 8e45c38dae14
Revises: 
Create Date: 2023-05-22 21:45:16.277177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e45c38dae14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('punters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horse', sa.String(), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('meeting', sa.String(), nullable=False),
    sa.Column('bet_type', sa.String(), nullable=False),
    sa.Column('min_price', sa.String(), nullable=False),
    sa.Column('stake', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('punter_id', sa.Integer(), nullable=True),
    sa.Column('tip_id', sa.Integer(), nullable=True),
    sa.Column('stake', sa.String(), nullable=False),
    sa.Column('price', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['punter_id'], ['punters.id'], ),
    sa.ForeignKeyConstraint(['tip_id'], ['tips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bets')
    op.drop_table('users')
    op.drop_table('tips')
    op.drop_table('punters')
    # ### end Alembic commands ###
