"""empty message

Revision ID: 9779b362a101
Revises: 
Create Date: 2023-05-21 11:35:04.214838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9779b362a101'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('punter_id', sa.String(), nullable=False),
    sa.Column('tip_id', sa.String(), nullable=False),
    sa.Column('stake', sa.String(), nullable=False),
    sa.Column('price', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('punters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horse', sa.String(), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('meeting', sa.String(), nullable=False),
    sa.Column('bet_type', sa.String(), nullable=False),
    sa.Column('min_price', sa.String(), nullable=False),
    sa.Column('stake', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tips')
    op.drop_table('punters')
    op.drop_table('bets')
    # ### end Alembic commands ###
